import gleam/list

pub type PopulationFilter {
  All
  TwentyMillion
  FiftyMillion
  HundredMillion
}

pub fn get_countries(all: PopulationFilter) -> List(#(String, String, String)) {
  case all {
    All -> all_countries
    TwentyMillion -> greater_than_20_million
    FiftyMillion -> greater_than_50_million
    HundredMillion -> greater_than_100_million
  }
  |> list.shuffle()
  |> list.take(15)
}

const greater_than_100_million = [
  #("bangladesh", "dhaka", "🇧🇩"), #("brazil", "brasilia", "🇧🇷"),
  #("china", "beijing", "🇨🇳"), #("egypt", "cairo", "🇪🇬"),
  #("ethiopia", "addis ababa", "🇪🇹"), #("india", "new delhi", "🇮🇳"),
  #("indonesia", "jakarta", "🇮🇩"), #("japan", "tokyo", "🇯🇵"),
  #("mexico", "mexico city", "🇲🇽"), #("nigeria", "abuja", "🇳🇬"),
  #("pakistan", "islamabad", "🇵🇰"), #("philippines", "manila", "🇵🇭"),
  #("russia", "moscow", "🇷🇺"),
  #("united states", "washington, dc", "🇺🇸"),
  #("vietnam", "hanoi", "🇻🇳"),
]

const greater_than_50_million = [
  #("afghanistan", "kabul", "🇦🇫"), #("algeria", "algiers", "🇩🇿"),
  #("bangladesh", "dhaka", "🇧🇩"), #("brazil", "brasilia", "🇧🇷"),
  #("china", "beijing", "🇨🇳"), #("colombia", "bogota", "🇨🇴"),
  #("democratic republic of the congo", "kinshasa", "🇨🇩"),
  #("egypt", "cairo", "🇪🇬"), #("ethiopia", "addis ababa", "🇪🇹"),
  #("france", "paris", "🇫🇷"), #("germany", "berlin", "🇩🇪"),
  #("india", "new delhi", "🇮🇳"), #("indonesia", "jakarta", "🇮🇩"),
  #("iran", "tehran", "🇮🇷"), #("italy", "rome", "🇮🇹"),
  #("japan", "tokyo", "🇯🇵"), #("kenya", "nairobi", "🇰🇪"),
  #("korea, south", "seoul", "🇰🇷"), #("mexico", "mexico city", "🇲🇽"),
  #("myanmar", "naypyidaw", "🇲🇲"), #("nigeria", "abuja", "🇳🇬"),
  #("pakistan", "islamabad", "🇵🇰"), #("philippines", "manila", "🇵🇭"),
  #("russia", "moscow", "🇷🇺"), #("south africa", "pretoria", "🇿🇦"),
  #("south korea", "seoul", "🇰🇷"), #("spain", "madrid", "🇪🇸"),
  #("tanzania", "dodoma", "🇹🇿"), #("thailand", "bangkok", "🇹🇭"),
  #("turkey", "ankara", "🇹🇷"), #("united kingdom", "london", "🇬🇧"),
  #("united states", "washington, dc", "🇺🇸"),
  #("vietnam", "hanoi", "🇻🇳"),
]

const greater_than_20_million = [
  #("afghanistan", "kabul", "🇦🇫"), #("algeria", "algiers", "🇩🇿"),
  #("angola", "luanda", "🇦🇴"), #("argentina", "buenos aires", "🇦🇷"),
  #("australia", "canberra", "🇦🇺"), #("bangladesh", "dhaka", "🇧🇩"),
  #("brazil", "brasilia", "🇧🇷"),
  #("burkina faso", "ouagadougou", "🇧🇫"),
  #("cameroon", "yaounde", "🇨🇲"), #("canada", "ottawa", "🇨🇦"),
  #("chad", "n'djamena", "🇹🇩"), #("chile", "santiago", "🇨🇱"),
  #("china", "beijing", "🇨🇳"), #("colombia", "bogota", "🇨🇴"),
  #("democratic republic of the congo", "kinshasa", "🇨🇩"),
  #("czech republic", "prague", "🇨🇿"),
  #("dominican republic", "santo domingo", "🇩🇴"),
  #("egypt", "cairo", "🇪🇬"), #("ethiopia", "addis ababa", "🇪🇹"),
  #("france", "paris", "🇫🇷"), #("ghana", "accra", "🇬🇭"),
  #("india", "new delhi", "🇮🇳"), #("indonesia", "jakarta", "🇮🇩"),
  #("iran", "tehran", "🇮🇷"), #("iraq", "baghdad", "🇮🇶"),
  #("italy", "rome", "🇮🇹"), #("japan", "tokyo", "🇯🇵"),
  #("kenya", "nairobi", "🇰🇪"), #("korea, north", "pyongyang", "🇰🇵"),
  #("korea, south", "seoul", "🇰🇷"),
  #("malaysia", "kuala lumpur", "🇲🇾"), #("morocco", "rabat", "🇲🇦"),
  #("mozambique", "maputo", "🇲🇿"), #("myanmar", "naypyidaw", "🇲🇲"),
  #("nepal", "kathmandu", "🇳🇵"), #("niger", "niamey", "🇳🇪"),
  #("nigeria", "abuja", "🇳🇬"), #("pakistan", "islamabad", "🇵🇰"),
  #("peru", "lima", "🇵🇪"), #("philippines", "manila", "🇵🇭"),
  #("poland", "warsaw", "🇵🇱"), #("russia", "moscow", "🇷🇺"),
  #("saudi arabia", "riyadh", "🇸🇦"),
  #("south africa", "pretoria", "🇿🇦"),
  #("south sudan", "juba", "🇸🇸"), #("spain", "madrid", "🇪🇸"),
  #("sri lanka", "kotte", "🇱🇰"), #("sudan", "khartoum", "🇸🇩"),
  #("tanzania", "dodoma", "🇹🇿"), #("thailand", "bangkok", "🇹🇭"),
  #("turkey", "ankara", "🇹🇷"), #("uganda", "kampala", "🇺🇬"),
  #("ukraine", "kyiv", "🇺🇦"), #("united kingdom", "london", "🇬🇧"),
  #("united states", "washington, dc", "🇺🇸"),
  #("uzbekistan", "tashkent", "🇺🇿"), #("venezuela", "caracas", "🇻🇪"),
  #("vietnam", "hanoi", "🇻🇳"), #("yemen", "sana'a", "🇾🇪"),
]

const all_countries = [
  #("afghanistan", "kabul", "🇦🇫"),
  #("argentina", "buenos aires", "🇦🇷"),
  #("australia", "canberra", "🇦🇺"), #("austria", "vienna", "🇦🇹"),
  #("bangladesh", "dhaka", "🇧🇩"), #("belarus", "minsk", "🇧🇾"),
  #("belgium", "brussels", "🇧🇪"), #("bolivia", "sucre", "🇧🇴"),
  #("bosnia and herzegovina", "sarajevo", "🇧🇦"),
  #("costa rica", "san jose", "🇨🇷"), #("croatia", "zagreb", "🇭🇷"),
  #("cuba", "havana", "🇨🇺"), #("brazil", "brasília", "🇧🇷"),
  #("canada", "ottawa", "🇨🇦"), #("chile", "santiago", "🇨🇱"),
  #("china", "beijing", "🇨🇳"), #("colombia", "bogota", "🇨🇴"),
  #("finland", "helsinki", "🇫🇮"), #("france", "paris", "🇫🇷"),
  #("bulgaria", "sofia", "🇧🇬"), #("czech republic", "prague", "🇨🇿"),
  #("denmark", "copenhagen", "🇩🇰"),
  #("dominican republic", "santo domingo", "🇩🇴"),
  #("ecuador", "quito", "🇪🇨"), #("egypt", "cairo", "🇪🇬"),
  #("germany", "berlin", "🇩🇪"), #("ghana", "accra", "🇬🇭"),
  #("greece", "athens", "🇬🇷"),
  #("guatemala", "guatemala city", "🇬🇹"),
  #("hungary", "budapest", "🇭🇺"), #("iceland", "reykjavik", "🇮🇸"),
  #("india", "new delhi", "🇮🇳"), #("indonesia", "jakarta", "🇮🇩"),
  #("iran", "tehran", "🇮🇷"), #("iraq", "baghdad", "🇮🇶"),
  #("ireland", "dublin", "🇮🇪"), #("italy", "rome", "🇮🇹"),
  #("jamaica", "kingston", "🇯🇲"), #("japan", "tokyo", "🇯🇵"),
  #("north korea", "pyongyang", "🇰🇵"),
  #("south korea", "seoul", "🇰🇷"), #("lebanon", "beirut", "🇱🇧"),
  #("libya", "tripoli", "🇱🇾"), #("mexico", "mexico city", "🇲🇽"),
  #("netherlands", "amsterdam", "🇳🇱"),
  #("new zealand", "wellington", "🇳🇿"), #("norway", "oslo", "🇳🇴"),
  #("pakistan", "islamabad", "🇵🇰"), #("peru", "lima", "🇵🇪"),
  #("philippines", "manila", "🇵🇭"), #("poland", "warsaw", "🇵🇱"),
  #("portugal", "lisbon", "🇵🇹"), #("romania", "bucharest", "🇷🇴"),
  #("russia", "moscow", "🇷🇺"), #("rwanda", "kigali", "🇷🇼"),
  #("spain", "madrid", "🇪🇸"), #("sweden", "stockholm", "🇸🇪"),
  #("thailand", "bangkok", "🇹🇭"), #("turkey", "ankara", "🇹🇷"),
  #("ukraine", "kyiv", "🇺🇦"),
  #("united arab emirates", "abu dhabi", "🇦🇪"),
  #("united kingdom", "london", "🇬🇧"),
  #("united states", "washington, dc", "🇺🇸"),
  #("venezuela", "caracas", "🇻🇪"), #("vietnam", "hanoi", "🇻🇳"),
  #("albania", "tirana", "🇦🇱"), #("algeria", "algiers", "🇩🇿"),
  #("andorra", "andorra la vella", "🇦🇩"),
  #("angola", "luanda", "🇦🇴"),
  #("antigua and barbuda", "saint john's", "🇦🇬"),
  #("armenia", "yerevan", "🇦🇲"), #("azerbaijan", "baku", "🇦🇿"),
  #("bahamas", "nassau", "🇧🇸"), #("bahrain", "manama", "🇧🇭"),
  #("barbados", "bridgetown", "🇧🇧"), #("belize", "belmopan", "🇧🇿"),
  #("benin", "porto-novo", "🇧🇯"), #("bhutan", "thimphu", "🇧🇹"),
  #("botswana", "gaborone", "🇧🇼"),
  #("brunei", "bandar seri begawan", "🇧🇳"),
  #("burkina faso", "ouagadougou", "🇧🇫"),
  #("burundi", "gitega", "🇧🇮"), #("cabo verde", "praia", "🇨🇻"),
  #("cambodia", "phnom penh", "🇰🇭"), #("cameroon", "yaoundé", "🇨🇲"),
  #("central african republic", "bangui", "🇨🇫"),
  #("chad", "n'djamena", "🇹🇩"), #("comoros", "moroni", "🇰🇲"),
  #("democratic republic of the congo", "kinshasa", "🇨🇩"),
  #("republic of the congo", "brazzaville", "🇨🇬"),
  #("cyprus", "nicosia", "🇨🇾"), #("djibouti", "djibouti", "🇩🇯"),
  #("dominica", "roseau", "🇩🇲"),
  #("el salvador", "san salvador", "🇸🇻"),
  #("equatorial guinea", "malabo", "🇬🇶"),
  #("eritrea", "asmara", "🇪🇷"), #("estonia", "tallinn", "🇪🇪"),
  #("eswatini", "mbabane", "🇸🇿"), #("ethiopia", "addis ababa", "🇪🇹"),
  #("fiji", "suva", "🇫🇯"), #("gabon", "libreville", "🇬🇦"),
  #("gambia", "banjul", "🇬🇲"), #("georgia", "tbilisi", "🇬🇪"),
  #("grenada", "saint george's", "🇬🇩"), #("guinea", "conakry", "🇬🇳"),
  #("guinea-bissau", "bissau", "🇬🇼"),
  #("guyana", "georgetown", "🇬🇾"),
  #("haiti", "port-au-prince", "🇭🇹"),
  #("honduras", "tegucigalpa", "🇭🇳"), #("jordan", "amman", "🇯🇴"),
  #("kazakhstan", "nur-sultan", "🇰🇿"), #("kenya", "nairobi", "🇰🇪"),
  #("kiribati", "tarawa", "🇰🇮"), #("kosovo", "pristina", "🇽🇰"),
  #("kuwait", "kuwait city", "🇰🇼"), #("kyrgyzstan", "bishkek", "🇰🇬"),
  #("laos", "vientiane", "🇱🇦"), #("latvia", "riga", "🇱🇻"),
  #("lesotho", "maseru", "🇱🇸"), #("liberia", "monrovia", "🇱🇷"),
  #("liechtenstein", "vaduz", "🇱🇮"), #("lithuania", "vilnius", "🇱🇹"),
  #("luxembourg", "luxembourg", "🇱🇺"),
  #("madagascar", "antananarivo", "🇲🇬"),
  #("malawi", "lilongwe", "🇲🇼"), #("malaysia", "kuala lumpur", "🇲🇾"),
  #("maldives", "male", "🇲🇻"), #("mali", "bamako", "🇲🇱"),
  #("malta", "valletta", "🇲🇹"),
  #("marshall islands", "majuro", "🇲🇭"),
  #("mauritania", "nouakchott", "🇲🇷"),
  #("mauritius", "port louis", "🇲🇺"),
  #("micronesia", "palikir", "🇫🇲"), #("moldova", "chisinau", "🇲🇩"),
  #("monaco", "monaco", "🇲🇨"), #("mongolia", "ulaanbaatar", "🇲🇳"),
  #("montenegro", "podgorica", "🇲🇪"), #("morocco", "rabat", "🇲🇦"),
  #("mozambique", "maputo", "🇲🇿"), #("myanmar", "naypyidaw", "🇲🇲"),
  #("namibia", "windhoek", "🇳🇦"), #("nauru", "yaren district", "🇳🇷"),
  #("nepal", "kathmandu", "🇳🇵"), #("nicaragua", "managua", "🇳🇮"),
  #("niger", "niamey", "🇳🇪"), #("nigeria", "abuja", "🇳🇬"),
  #("north macedonia", "skopje", "🇲🇰"), #("oman", "muscat", "🇴🇲"),
  #("palau", "ngerulmud", "🇵🇼"), #("panama", "panama city", "🇵🇦"),
  #("papua new guinea", "port moresby", "🇵🇬"),
  #("paraguay", "asuncion", "🇵🇾"), #("qatar", "doha", "🇶🇦"),
  #("saint kitts and nevis", "basseterre", "🇰🇳"),
  #("saint lucia", "castries", "🇱🇨"),
  #("saint vincent and the grenadines", "kingstown", "🇻🇨"),
  #("samoa", "apia", "🇼🇸"), #("san marino", "san marino", "🇸🇲"),
  #("sao tome and principe", "sao tome", "🇸🇹"),
  #("saudi arabia", "riyadh", "🇸🇦"), #("senegal", "dakar", "🇸🇳"),
  #("serbia", "belgrade", "🇷🇸"), #("seychelles", "victoria", "🇸🇨"),
  #("sierra leone", "freetown", "🇸🇱"),
  #("singapore", "singapore", "🇸🇬"),
  #("slovakia", "bratislava", "🇸🇰"),
  #("slovenia", "ljubljana", "🇸🇮"),
  #("solomon islands", "honiara", "🇸🇧"),
  #("somalia", "mogadishu", "🇸🇴"),
  #("south africa", "pretoria", "🇿🇦"),
  #("south sudan", "juba", "🇸🇸"), #("sri lanka", "kotte", "🇱🇰"),
  #("sudan", "khartoum", "🇸🇩"), #("suriname", "paramaribo", "🇸🇷"),
  #("switzerland", "bern", "🇨🇭"), #("syria", "damascus", "🇸🇾"),
  #("taiwan", "taipei", "🇹🇼"), #("tajikistan", "dushanbe", "🇹🇯"),
  #("tanzania", "dodoma", "🇹🇿"), #("timor-leste", "dili", "🇹🇱"),
  #("togo", "lome", "🇹🇬"), #("tonga", "nuku'alofa", "🇹🇴"),
  #("trinidad and tobago", "port of spain", "🇹🇹"),
  #("tunisia", "tunis", "🇹🇳"), #("turkmenistan", "ashgabat", "🇹🇲"),
  #("tuvalu", "funafuti", "🇹🇻"), #("uganda", "kampala", "🇺🇬"),
  #("uruguay", "montevideo", "🇺🇾"),
  #("uzbekistan", "tashkent", "🇺🇿"), #("vanuatu", "port vila", "🇻🇺"),
  #("vatican city", "vatican city", "🇻🇦"),
  #("yemen", "sana'a", "🇾🇪"), #("zambia", "lusaka", "🇿🇲"),
  #("zimbabwe", "harare", "🇿🇼"),
]
