import gleam/list

pub fn get_countries(
  continents: List(String),
) -> List(#(String, String, String)) {
  continents
  |> list.map(fn(c: String) -> List(#(String, String, String)) {
    case c {
      "americas" -> americas
      "europe" -> europe
      "asia" -> asia
      "africa" -> africa
      "oceania" -> oceania
      _ -> americas
    }
  })
  |> list.flatten()
  |> list.shuffle()
  |> list.take(15)
}

const americas = [
  #("argentina", "buenos aires", "🇦🇷"), #("bolivia", "sucre", "🇧🇴"),
  #("brazil", "brasília", "🇧🇷"), #("canada", "ottawa", "🇨🇦"),
  #("chile", "santiago", "🇨🇱"), #("colombia", "bogota", "🇨🇴"),
  #("costa rica", "san jose", "🇨🇷"), #("cuba", "havana", "🇨🇺"),
  #("dominican republic", "santo domingo", "🇩🇴"),
  #("ecuador", "quito", "🇪🇨"),
  #("el salvador", "san salvador", "🇸🇻"),
  #("guatemala", "guatemala city", "🇬🇹"),
  #("haiti", "port-au-prince", "🇭🇹"),
  #("honduras", "tegucigalpa", "🇭🇳"), #("jamaica", "kingston", "🇯🇲"),
  #("mexico", "mexico city", "🇲🇽"), #("nicaragua", "managua", "🇳🇮"),
  #("panama", "panama city", "🇵🇦"), #("paraguay", "asuncion", "🇵🇾"),
  #("peru", "lima", "🇵🇪"),
  #("trinidad and tobago", "port of spain", "🇹🇹"),
  #("united states", "washington, dc", "🇺🇸"),
  #("uruguay", "montevideo", "🇺🇾"), #("venezuela", "caracas", "🇻🇪"),
  #("belize", "belmopan", "🇧🇿"), #("bahamas", "nassau", "🇧🇸"),
  #("antigua and barbuda", "saint john's", "🇦🇬"),
  #("barbados", "bridgetown", "🇧🇧"),
  #("grenada", "saint george's", "🇬🇩"),
  #("guyana", "georgetown", "🇬🇾"),
  #("saint kitts and nevis", "basseterre", "🇰🇳"),
  #("saint lucia", "castries", "🇱🇨"),
  #("saint vincent and the grenadines", "kingstown", "🇻🇨"),
  #("suriname", "paramaribo", "🇸🇷"),
]

const europe = [
  #("austria", "vienna", "🇦🇹"), #("belarus", "minsk", "🇧🇾"),
  #("belgium", "brussels", "🇧🇪"),
  #("bosnia and herzegovina", "sarajevo", "🇧🇦"),
  #("bulgaria", "sofia", "🇧🇬"), #("croatia", "zagreb", "🇭🇷"),
  #("czech republic", "prague", "🇨🇿"),
  #("denmark", "copenhagen", "🇩🇰"), #("finland", "helsinki", "🇫🇮"),
  #("france", "paris", "🇫🇷"), #("germany", "berlin", "🇩🇪"),
  #("greece", "athens", "🇬🇷"), #("hungary", "budapest", "🇭🇺"),
  #("iceland", "reykjavik", "🇮🇸"), #("ireland", "dublin", "🇮🇪"),
  #("italy", "rome", "🇮🇹"), #("latvia", "riga", "🇱🇻"),
  #("lithuania", "vilnius", "🇱🇹"),
  #("luxembourg", "luxembourg", "🇱🇺"), #("malta", "valletta", "🇲🇹"),
  #("netherlands", "amsterdam", "🇳🇱"), #("norway", "oslo", "🇳🇴"),
  #("poland", "warsaw", "🇵🇱"), #("portugal", "lisbon", "🇵🇹"),
  #("romania", "bucharest", "🇷🇴"), #("russia", "moscow", "🇷🇺"),
  #("serbia", "belgrade", "🇷🇸"), #("slovakia", "bratislava", "🇸🇰"),
  #("slovenia", "ljubljana", "🇸🇮"), #("spain", "madrid", "🇪🇸"),
  #("sweden", "stockholm", "🇸🇪"), #("switzerland", "bern", "🇨🇭"),
  #("ukraine", "kyiv", "🇺🇦"), #("united kingdom", "london", "🇬🇧"),
  #("albania", "tirana", "🇦🇱"),
  #("andorra", "andorra la vella", "🇦🇩"),
  #("armenia", "yerevan", "🇦🇲"), #("azerbaijan", "baku", "🇦🇿"),
  #("cyprus", "nicosia", "🇨🇾"), #("estonia", "tallinn", "🇪🇪"),
  #("georgia", "tbilisi", "🇬🇪"), #("kosovo", "pristina", "🇽🇰"),
  #("liechtenstein", "vaduz", "🇱🇮"), #("moldova", "chisinau", "🇲🇩"),
  #("monaco", "monaco", "🇲🇨"), #("montenegro", "podgorica", "🇲🇪"),
  #("north macedonia", "skopje", "🇲🇰"),
  #("san marino", "san marino", "🇸🇲"),
  #("vatican city", "vatican city", "🇻🇦"),
]

const asia = [
  #("afghanistan", "kabul", "🇦🇫"), #("bangladesh", "dhaka", "🇧🇩"),
  #("bhutan", "thimphu", "🇧🇹"),
  #("brunei", "bandar seri begawan", "🇧🇳"),
  #("cambodia", "phnom penh", "🇰🇭"), #("china", "beijing", "🇨🇳"),
  #("india", "new delhi", "🇮🇳"), #("indonesia", "jakarta", "🇮🇩"),
  #("iran", "tehran", "🇮🇷"), #("iraq", "baghdad", "🇮🇶"),
  #("israel", "jerusalem", "🇮🇱"), #("japan", "tokyo", "🇯🇵"),
  #("jordan", "amman", "🇯🇴"), #("kazakhstan", "nur-sultan", "🇰🇿"),
  #("kuwait", "kuwait city", "🇰🇼"), #("kyrgyzstan", "bishkek", "🇰🇬"),
  #("laos", "vientiane", "🇱🇦"), #("lebanon", "beirut", "🇱🇧"),
  #("malaysia", "kuala lumpur", "🇲🇾"), #("maldives", "male", "🇲🇻"),
  #("mongolia", "ulaanbaatar", "🇲🇳"),
  #("myanmar", "naypyidaw", "🇲🇲"), #("nepal", "kathmandu", "🇳🇵"),
  #("north korea", "pyongyang", "🇰🇵"), #("oman", "muscat", "🇴🇲"),
  #("pakistan", "islamabad", "🇵🇰"), #("palestine", "ramallah", "🇵🇸"),
  #("philippines", "manila", "🇵🇭"), #("qatar", "doha", "🇶🇦"),
  #("saudi arabia", "riyadh", "🇸🇦"),
  #("singapore", "singapore", "🇸🇬"), #("south korea", "seoul", "🇰🇷"),
  #("sri lanka", "kotte", "🇱🇰"), #("syria", "damascus", "🇸🇾"),
  #("taiwan", "taipei", "🇹🇼"), #("tajikistan", "dushanbe", "🇹🇯"),
  #("thailand", "bangkok", "🇹🇭"), #("turkey", "ankara", "🇹🇷"),
  #("turkmenistan", "ashgabat", "🇹🇲"),
  #("united arab emirates", "abu dhabi", "🇦🇪"),
  #("uzbekistan", "tashkent", "🇺🇿"), #("vietnam", "hanoi", "🇻🇳"),
  #("yemen", "sana'a", "🇾🇪"),
]

const africa = [
  #("algeria", "algiers", "🇩🇿"), #("angola", "luanda", "🇦🇴"),
  #("benin", "porto-novo", "🇧🇯"), #("botswana", "gaborone", "🇧🇼"),
  #("burkina faso", "ouagadougou", "🇧🇫"),
  #("burundi", "gitega", "🇧🇮"), #("cabo verde", "praia", "🇨🇻"),
  #("cameroon", "yaoundé", "🇨🇲"),
  #("central african republic", "bangui", "🇨🇫"),
  #("chad", "n'djamena", "🇹🇩"), #("comoros", "moroni", "🇰🇲"),
  #("democratic republic of the congo", "kinshasa", "🇨🇩"),
  #("republic of the congo", "brazzaville", "🇨🇬"),
  #("djibouti", "djibouti", "🇩🇯"), #("egypt", "cairo", "🇪🇬"),
  #("equatorial guinea", "malabo", "🇬🇶"),
  #("eritrea", "asmara", "🇪🇷"), #("eswatini", "mbabane", "🇸🇿"),
  #("ethiopia", "addis ababa", "🇪🇹"), #("gabon", "libreville", "🇬🇦"),
  #("gambia", "banjul", "🇬🇲"), #("ghana", "accra", "🇬🇭"),
  #("guinea", "conakry", "🇬🇳"), #("guinea-bissau", "bissau", "🇬🇼"),
  #("ivory coast", "yamoussoukro", "🇨🇮"),
  #("kenya", "nairobi", "🇰🇪"), #("lesotho", "maseru", "🇱🇸"),
  #("liberia", "monrovia", "🇱🇷"), #("libya", "tripoli", "🇱🇾"),
  #("madagascar", "antananarivo", "🇲🇬"),
  #("malawi", "lilongwe", "🇲🇼"), #("mali", "bamako", "🇲🇱"),
  #("mauritania", "nouakchott", "🇲🇷"),
  #("mauritius", "port louis", "🇲🇺"), #("morocco", "rabat", "🇲🇦"),
  #("mozambique", "maputo", "🇲🇿"), #("namibia", "windhoek", "🇳🇦"),
  #("niger", "niamey", "🇳🇪"), #("nigeria", "abuja", "🇳🇬"),
  #("rwanda", "kigali", "🇷🇼"),
  #("sao tome and principe", "sao tome", "🇸🇹"),
  #("senegal", "dakar", "🇸🇳"), #("seychelles", "victoria", "🇸🇨"),
  #("sierra leone", "freetown", "🇸🇱"),
  #("somalia", "mogadishu", "🇸🇴"),
  #("south africa", "pretoria", "🇿🇦"),
  #("south sudan", "juba", "🇸🇸"), #("sudan", "khartoum", "🇸🇩"),
  #("tanzania", "dodoma", "🇹🇿"), #("togo", "lome", "🇹🇬"),
  #("tunisia", "tunis", "🇹🇳"), #("uganda", "kampala", "🇺🇬"),
  #("zambia", "lusaka", "🇿🇲"), #("zimbabwe", "harare", "🇿🇼"),
]

const oceania = [
  #("australia", "canberra", "🇦🇺"), #("fiji", "suva", "🇫🇯"),
  #("kiribati", "tarawa", "🇰🇮"),
  #("marshall islands", "majuro", "🇲🇭"),
  #("micronesia", "palikir", "🇫🇲"),
  #("nauru", "yaren district", "🇳🇷"),
  #("new zealand", "wellington", "🇳🇿"),
  #("palau", "ngerulmud", "🇵🇼"),
  #("papua new guinea", "port moresby", "🇵🇬"),
  #("samoa", "apia", "🇼🇸"), #("solomon islands", "honiara", "🇸🇧"),
  #("tonga", "nuku'alofa", "🇹🇴"), #("tuvalu", "funafuti", "🇹🇻"),
  #("vanuatu", "port vila", "🇻🇺"),
]

const all_countries = [
  #("afghanistan", "kabul", "🇦🇫"),
  #("argentina", "buenos aires", "🇦🇷"),
  #("australia", "canberra", "🇦🇺"), #("austria", "vienna", "🇦🇹"),
  #("bangladesh", "dhaka", "🇧🇩"), #("belarus", "minsk", "🇧🇾"),
  #("belgium", "brussels", "🇧🇪"), #("bolivia", "sucre", "🇧🇴"),
  #("bosnia and herzegovina", "sarajevo", "🇧🇦"),
  #("costa rica", "san jose", "🇨🇷"), #("croatia", "zagreb", "🇭🇷"),
  #("cuba", "havana", "🇨🇺"), #("brazil", "brasília", "🇧🇷"),
  #("canada", "ottawa", "🇨🇦"), #("chile", "santiago", "🇨🇱"),
  #("china", "beijing", "🇨🇳"), #("colombia", "bogota", "🇨🇴"),
  #("finland", "helsinki", "🇫🇮"), #("france", "paris", "🇫🇷"),
  #("bulgaria", "sofia", "🇧🇬"), #("czech republic", "prague", "🇨🇿"),
  #("denmark", "copenhagen", "🇩🇰"),
  #("dominican republic", "santo domingo", "🇩🇴"),
  #("ecuador", "quito", "🇪🇨"), #("egypt", "cairo", "🇪🇬"),
  #("germany", "berlin", "🇩🇪"), #("ghana", "accra", "🇬🇭"),
  #("greece", "athens", "🇬🇷"),
  #("guatemala", "guatemala city", "🇬🇹"),
  #("hungary", "budapest", "🇭🇺"), #("iceland", "reykjavik", "🇮🇸"),
  #("india", "new delhi", "🇮🇳"), #("indonesia", "jakarta", "🇮🇩"),
  #("iran", "tehran", "🇮🇷"), #("iraq", "baghdad", "🇮🇶"),
  #("ireland", "dublin", "🇮🇪"), #("italy", "rome", "🇮🇹"),
  #("jamaica", "kingston", "🇯🇲"), #("japan", "tokyo", "🇯🇵"),
  #("north korea", "pyongyang", "🇰🇵"),
  #("south korea", "seoul", "🇰🇷"), #("lebanon", "beirut", "🇱🇧"),
  #("libya", "tripoli", "🇱🇾"), #("mexico", "mexico city", "🇲🇽"),
  #("netherlands", "amsterdam", "🇳🇱"),
  #("new zealand", "wellington", "🇳🇿"), #("norway", "oslo", "🇳🇴"),
  #("pakistan", "islamabad", "🇵🇰"), #("peru", "lima", "🇵🇪"),
  #("philippines", "manila", "🇵🇭"), #("poland", "warsaw", "🇵🇱"),
  #("portugal", "lisbon", "🇵🇹"), #("romania", "bucharest", "🇷🇴"),
  #("russia", "moscow", "🇷🇺"), #("rwanda", "kigali", "🇷🇼"),
  #("spain", "madrid", "🇪🇸"), #("sweden", "stockholm", "🇸🇪"),
  #("thailand", "bangkok", "🇹🇭"), #("turkey", "ankara", "🇹🇷"),
  #("ukraine", "kyiv", "🇺🇦"),
  #("united arab emirates", "abu dhabi", "🇦🇪"),
  #("united kingdom", "london", "🇬🇧"),
  #("united states", "washington, dc", "🇺🇸"),
  #("venezuela", "caracas", "🇻🇪"), #("vietnam", "hanoi", "🇻🇳"),
  #("albania", "tirana", "🇦🇱"), #("algeria", "algiers", "🇩🇿"),
  #("andorra", "andorra la vella", "🇦🇩"),
  #("angola", "luanda", "🇦🇴"),
  #("antigua and barbuda", "saint john's", "🇦🇬"),
  #("armenia", "yerevan", "🇦🇲"), #("azerbaijan", "baku", "🇦🇿"),
  #("bahamas", "nassau", "🇧🇸"), #("bahrain", "manama", "🇧🇭"),
  #("barbados", "bridgetown", "🇧🇧"), #("belize", "belmopan", "🇧🇿"),
  #("benin", "porto-novo", "🇧🇯"), #("bhutan", "thimphu", "🇧🇹"),
  #("botswana", "gaborone", "🇧🇼"),
  #("brunei", "bandar seri begawan", "🇧🇳"),
  #("burkina faso", "ouagadougou", "🇧🇫"),
  #("burundi", "gitega", "🇧🇮"), #("cabo verde", "praia", "🇨🇻"),
  #("cambodia", "phnom penh", "🇰🇭"), #("cameroon", "yaoundé", "🇨🇲"),
  #("central african republic", "bangui", "🇨🇫"),
  #("chad", "n'djamena", "🇹🇩"), #("comoros", "moroni", "🇰🇲"),
  #("democratic republic of the congo", "kinshasa", "🇨🇩"),
  #("republic of the congo", "brazzaville", "🇨🇬"),
  #("cyprus", "nicosia", "🇨🇾"), #("djibouti", "djibouti", "🇩🇯"),
  #("dominica", "roseau", "🇩🇲"),
  #("el salvador", "san salvador", "🇸🇻"),
  #("equatorial guinea", "malabo", "🇬🇶"),
  #("eritrea", "asmara", "🇪🇷"), #("estonia", "tallinn", "🇪🇪"),
  #("eswatini", "mbabane", "🇸🇿"), #("ethiopia", "addis ababa", "🇪🇹"),
  #("fiji", "suva", "🇫🇯"), #("gabon", "libreville", "🇬🇦"),
  #("gambia", "banjul", "🇬🇲"), #("georgia", "tbilisi", "🇬🇪"),
  #("grenada", "saint george's", "🇬🇩"), #("guinea", "conakry", "🇬🇳"),
  #("guinea-bissau", "bissau", "🇬🇼"),
  #("guyana", "georgetown", "🇬🇾"),
  #("haiti", "port-au-prince", "🇭🇹"),
  #("honduras", "tegucigalpa", "🇭🇳"), #("jordan", "amman", "🇯🇴"),
  #("kazakhstan", "nur-sultan", "🇰🇿"), #("kenya", "nairobi", "🇰🇪"),
  #("kiribati", "tarawa", "🇰🇮"), #("kosovo", "pristina", "🇽🇰"),
  #("kuwait", "kuwait city", "🇰🇼"), #("kyrgyzstan", "bishkek", "🇰🇬"),
  #("laos", "vientiane", "🇱🇦"), #("latvia", "riga", "🇱🇻"),
  #("lesotho", "maseru", "🇱🇸"), #("liberia", "monrovia", "🇱🇷"),
  #("liechtenstein", "vaduz", "🇱🇮"), #("lithuania", "vilnius", "🇱🇹"),
  #("luxembourg", "luxembourg", "🇱🇺"),
  #("madagascar", "antananarivo", "🇲🇬"),
  #("malawi", "lilongwe", "🇲🇼"), #("malaysia", "kuala lumpur", "🇲🇾"),
  #("maldives", "male", "🇲🇻"), #("mali", "bamako", "🇲🇱"),
  #("malta", "valletta", "🇲🇹"),
  #("marshall islands", "majuro", "🇲🇭"),
  #("mauritania", "nouakchott", "🇲🇷"),
  #("mauritius", "port louis", "🇲🇺"),
  #("micronesia", "palikir", "🇫🇲"), #("moldova", "chisinau", "🇲🇩"),
  #("monaco", "monaco", "🇲🇨"), #("mongolia", "ulaanbaatar", "🇲🇳"),
  #("montenegro", "podgorica", "🇲🇪"), #("morocco", "rabat", "🇲🇦"),
  #("mozambique", "maputo", "🇲🇿"), #("myanmar", "naypyidaw", "🇲🇲"),
  #("namibia", "windhoek", "🇳🇦"), #("nauru", "yaren district", "🇳🇷"),
  #("nepal", "kathmandu", "🇳🇵"), #("nicaragua", "managua", "🇳🇮"),
  #("niger", "niamey", "🇳🇪"), #("nigeria", "abuja", "🇳🇬"),
  #("north macedonia", "skopje", "🇲🇰"), #("oman", "muscat", "🇴🇲"),
  #("palau", "ngerulmud", "🇵🇼"), #("panama", "panama city", "🇵🇦"),
  #("papua new guinea", "port moresby", "🇵🇬"),
  #("paraguay", "asuncion", "🇵🇾"), #("qatar", "doha", "🇶🇦"),
  #("saint kitts and nevis", "basseterre", "🇰🇳"),
  #("saint lucia", "castries", "🇱🇨"),
  #("saint vincent and the grenadines", "kingstown", "🇻🇨"),
  #("samoa", "apia", "🇼🇸"), #("san marino", "san marino", "🇸🇲"),
  #("sao tome and principe", "sao tome", "🇸🇹"),
  #("saudi arabia", "riyadh", "🇸🇦"), #("senegal", "dakar", "🇸🇳"),
  #("serbia", "belgrade", "🇷🇸"), #("seychelles", "victoria", "🇸🇨"),
  #("sierra leone", "freetown", "🇸🇱"),
  #("singapore", "singapore", "🇸🇬"),
  #("slovakia", "bratislava", "🇸🇰"),
  #("slovenia", "ljubljana", "🇸🇮"),
  #("solomon islands", "honiara", "🇸🇧"),
  #("somalia", "mogadishu", "🇸🇴"),
  #("south africa", "pretoria", "🇿🇦"),
  #("south sudan", "juba", "🇸🇸"), #("sri lanka", "kotte", "🇱🇰"),
  #("sudan", "khartoum", "🇸🇩"), #("suriname", "paramaribo", "🇸🇷"),
  #("switzerland", "bern", "🇨🇭"), #("syria", "damascus", "🇸🇾"),
  #("taiwan", "taipei", "🇹🇼"), #("tajikistan", "dushanbe", "🇹🇯"),
  #("tanzania", "dodoma", "🇹🇿"), #("timor-leste", "dili", "🇹🇱"),
  #("togo", "lome", "🇹🇬"), #("tonga", "nuku'alofa", "🇹🇴"),
  #("trinidad and tobago", "port of spain", "🇹🇹"),
  #("tunisia", "tunis", "🇹🇳"), #("turkmenistan", "ashgabat", "🇹🇲"),
  #("tuvalu", "funafuti", "🇹🇻"), #("uganda", "kampala", "🇺🇬"),
  #("uruguay", "montevideo", "🇺🇾"),
  #("uzbekistan", "tashkent", "🇺🇿"), #("vanuatu", "port vila", "🇻🇺"),
  #("vatican city", "vatican city", "🇻🇦"),
  #("yemen", "sana'a", "🇾🇪"), #("zambia", "lusaka", "🇿🇲"),
  #("zimbabwe", "harare", "🇿🇼"),
]
