import gleam/float
import gleam/list
import gleam/order

pub fn get_countries(
  continents: List(String),
  population_filter: Bool,
) -> List(#(String, String, String, Float)) {
  continents
  |> list.map(fn(c: String) -> List(#(String, String, String, Float)) {
    case c {
      "americas" -> americas
      "europe" -> europe
      "asia" -> asia
      "africa" -> africa
      "oceania" -> oceania
      _ -> []
    }
  })
  |> list.flatten()
  |> fn(countries: List(#(String, String, String, Float))) {
    case population_filter {
      True ->
        list.filter(countries, fn(c: #(String, String, String, Float)) {
          float.compare(c.3, 10.0) == order.Gt
        })
      False -> countries
    }
  }
  |> list.shuffle()
  |> list.take(15)
}

const americas = [
  #("argentina", "buenos aires", "🇦🇷", 45.38),
  #("bolivia", "sucre", "🇧🇴", 11.67),
  #("brazil", "brasilia", "🇧🇷", 213.99),
  #("canada", "ottawa", "🇨🇦", 38.05),
  #("chile", "santiago", "🇨🇱", 19.49),
  #("colombia", "bogota", "🇨🇴", 51.27),
  #("costa rica", "san jose", "🇨🇷", 5.17),
  #("cuba", "havana", "🇨🇺", 11.32),
  #("dominican republic", "santo domingo", "🇩🇴", 10.85),
  #("ecuador", "quito", "🇪🇨", 17.89),
  #("el salvador", "san salvador", "🇸🇻", 6.49),
  #("guatemala", "guatemala city", "🇬🇹", 18.28),
  #("haiti", "port-au-prince", "🇭🇹", 11.4),
  #("honduras", "tegucigalpa", "🇭🇳", 10.12),
  #("jamaica", "kingston", "🇯🇲", 2.97),
  #("mexico", "mexico city", "🇲🇽", 126.19),
  #("nicaragua", "managua", "🇳🇮", 6.85),
  #("panama", "panama city", "🇵🇦", 4.41),
  #("paraguay", "asuncion", "🇵🇾", 7.25),
  #("peru", "lima", "🇵🇪", 33.83),
  #("trinidad and tobago", "port of spain", "🇹🇹", 1.4),
  #("united states", "washington, dc", "🇺🇸", 331.89),
  #("uruguay", "montevideo", "🇺🇾", 3.47),
  #("venezuela", "caracas", "🇻🇪", 28.44),
  #("belize", "belmopan", "🇧🇿", 0.43),
  #("bahamas", "nassau", "🇧🇸", 0.39),
  #("antigua and barbuda", "saint john's", "🇦🇬", 0.1),
  #("barbados", "bridgetown", "🇧🇧", 0.29),
  #("grenada", "saint george's", "🇬🇩", 0.11),
  #("guyana", "georgetown", "🇬🇾", 0.79),
  #("saint kitts and nevis", "basseterre", "🇰🇳", 0.05),
  #("saint lucia", "castries", "🇱🇨", 0.18),
  #("saint vincent and the grenadines", "kingstown", "🇻🇨", 0.11),
  #("suriname", "paramaribo", "🇸🇷", 0.62),
]

const europe = [
  #("austria", "vienna", "🇦🇹", 8.95),
  #("belarus", "minsk", "🇧🇾", 9.44),
  #("belgium", "brussels", "🇧🇪", 11.56),
  #("bosnia and herzegovina", "sarajevo", "🇧🇦", 3.28),
  #("bulgaria", "sofia", "🇧🇬", 6.89),
  #("croatia", "zagreb", "🇭🇷", 4.05),
  #("czech republic", "prague", "🇨🇿", 10.7),
  #("denmark", "copenhagen", "🇩🇰", 5.84),
  #("finland", "helsinki", "🇫🇮", 5.55),
  #("france", "paris", "🇫🇷", 67.39),
  #("germany", "berlin", "🇩🇪", 83.24),
  #("greece", "athens", "🇬🇷", 10.39),
  #("hungary", "budapest", "🇭🇺", 9.63),
  #("iceland", "reykjavik", "🇮🇸", 0.37),
  #("ireland", "dublin", "🇮🇪", 4.98),
  #("italy", "rome", "🇮🇹", 59.55), #("latvia", "riga", "🇱🇻", 1.87),
  #("lithuania", "vilnius", "🇱🇹", 2.79),
  #("luxembourg", "luxembourg", "🇱🇺", 0.64),
  #("malta", "valletta", "🇲🇹", 0.52),
  #("netherlands", "amsterdam", "🇳🇱", 17.44),
  #("norway", "oslo", "🇳🇴", 5.42),
  #("poland", "warsaw", "🇵🇱", 37.95),
  #("portugal", "lisbon", "🇵🇹", 10.31),
  #("romania", "bucharest", "🇷🇴", 19.13),
  #("russia", "moscow", "🇷🇺", 144.1),
  #("serbia", "belgrade", "🇷🇸", 6.73),
  #("slovakia", "bratislava", "🇸🇰", 5.46),
  #("slovenia", "ljubljana", "🇸🇮", 2.1),
  #("spain", "madrid", "🇪🇸", 47.35),
  #("sweden", "stockholm", "🇸🇪", 10.35),
  #("switzerland", "bern", "🇨🇭", 8.6),
  #("ukraine", "kyiv", "🇺🇦", 41.17),
  #("united kingdom", "london", "🇬🇧", 67.22),
  #("albania", "tirana", "🇦🇱", 2.87),
  #("andorra", "andorra la vella", "🇦🇩", 0.08),
  #("armenia", "yerevan", "🇦🇲", 2.96),
  #("azerbaijan", "baku", "🇦🇿", 10.1),
  #("cyprus", "nicosia", "🇨🇾", 1.21),
  #("estonia", "tallinn", "🇪🇪", 1.32),
  #("georgia", "tbilisi", "🇬🇪", 3.72),
  #("kosovo", "pristina", "🇽🇰", 1.8),
  #("liechtenstein", "vaduz", "🇱🇮", 0.04),
  #("moldova", "chisinau", "🇲🇩", 2.62),
  #("monaco", "monaco", "🇲🇨", 0.04),
  #("montenegro", "podgorica", "🇲🇪", 0.62),
  #("north macedonia", "skopje", "🇲🇰", 2.08),
  #("san marino", "san marino", "🇸🇲", 0.03),
  #("vatican city", "vatican city", "🇻🇦", 0.0),
]

const africa = [
  #("algeria", "algiers", "🇩🇿", 44.18),
  #("angola", "luanda", "🇦🇴", 34.8),
  #("benin", "porto-novo", "🇧🇯", 12.12),
  #("botswana", "gaborone", "🇧🇼", 2.39),
  #("burkina faso", "ouagadougou", "🇧🇫", 21.51),
  #("burundi", "gitega", "🇧🇮", 12.37),
  #("cabo verde", "praia", "🇨🇻", 0.56),
  #("cameroon", "yaoundé", "🇨🇲", 27.2),
  #("central african republic", "bangui", "🇨🇫", 5.45),
  #("chad", "n'djamena", "🇹🇩", 17.18),
  #("comoros", "moroni", "🇰🇲", 0.88),
  #("democratic republic of the congo", "kinshasa", "🇨🇩", 95.9),
  #("republic of the congo", "brazzaville", "🇨🇬", 5.66),
  #("djibouti", "djibouti", "🇩🇯", 1.02),
  #("egypt", "cairo", "🇪🇬", 104.26),
  #("equatorial guinea", "malabo", "🇬🇶", 1.45),
  #("eritrea", "asmara", "🇪🇷", 3.6),
  #("eswatini", "mbabane", "🇸🇿", 1.16),
  #("ethiopia", "addis ababa", "🇪🇹", 120.28),
  #("gabon", "libreville", "🇬🇦", 2.34),
  #("gambia", "banjul", "🇬🇲", 2.59),
  #("ghana", "accra", "🇬🇭", 31.07),
  #("guinea", "conakry", "🇬🇳", 13.49),
  #("guinea-bissau", "bissau", "🇬🇼", 2.06),
  #("ivory coast", "yamoussoukro", "🇨🇮", 26.38),
  #("kenya", "nairobi", "🇰🇪", 55.78),
  #("lesotho", "maseru", "🇱🇸", 2.14),
  #("liberia", "monrovia", "🇱🇷", 5.18),
  #("libya", "tripoli", "🇱🇾", 7.04),
  #("madagascar", "antananarivo", "🇲🇬", 28.92),
  #("malawi", "lilongwe", "🇲🇼", 20.18),
  #("mali", "bamako", "🇲🇱", 22.13),
  #("mauritania", "nouakchott", "🇲🇷", 4.65),
  #("mauritius", "port louis", "🇲🇺", 1.27),
  #("morocco", "rabat", "🇲🇦", 37.34),
  #("mozambique", "maputo", "🇲🇿", 33.93),
  #("namibia", "windhoek", "🇳🇦", 2.54),
  #("niger", "niamey", "🇳🇪", 25.25),
  #("nigeria", "abuja", "🇳🇬", 213.4),
  #("rwanda", "kigali", "🇷🇼", 13.46),
  #("sao tome and principe", "sao tome", "🇸🇹", 0.23),
  #("senegal", "dakar", "🇸🇳", 17.22),
  #("seychelles", "victoria", "🇸🇨", 0.1),
  #("sierra leone", "freetown", "🇸🇱", 8.14),
  #("somalia", "mogadishu", "🇸🇴", 17.07),
  #("south africa", "pretoria", "🇿🇦", 59.39),
  #("south sudan", "juba", "🇸🇸", 11.38),
  #("sudan", "khartoum", "🇸🇩", 46.81),
  #("tanzania", "dodoma", "🇹🇿", 65.5), #("togo", "lome", "🇹🇬", 8.95),
  #("tunisia", "tunis", "🇹🇳", 12.11),
  #("uganda", "kampala", "🇺🇬", 48.58),
  #("zambia", "lusaka", "🇿🇲", 19.59),
  #("zimbabwe", "harare", "🇿🇼", 15.09),
]

const asia = [
  #("afghanistan", "kabul", "🇦🇫", 40.28),
  #("bangladesh", "dhaka", "🇧🇩", 166.3),
  #("bhutan", "thimphu", "🇧🇹", 0.78),
  #("brunei", "bandar seri begawan", "🇧🇳", 0.44),
  #("cambodia", "phnom penh", "🇰🇭", 17.0),
  #("china", "beijing", "🇨🇳", 1412.6),
  #("india", "new delhi", "🇮🇳", 1412.0),
  #("indonesia", "jakarta", "🇮🇩", 276.36),
  #("iran", "tehran", "🇮🇷", 85.02),
  #("iraq", "baghdad", "🇮🇶", 43.53),
  #("japan", "tokyo", "🇯🇵", 125.41),
  #("jordan", "amman", "🇯🇴", 10.3),
  #("kazakhstan", "nur-sultan", "🇰🇿", 19.28),
  #("kuwait", "kuwait city", "🇰🇼", 4.37),
  #("kyrgyzstan", "bishkek", "🇰🇬", 6.55),
  #("laos", "vientiane", "🇱🇦", 7.42),
  #("lebanon", "beirut", "🇱🇧", 6.7),
  #("malaysia", "kuala lumpur", "🇲🇾", 33.11),
  #("maldives", "male", "🇲🇻", 0.52),
  #("mongolia", "ulaanbaatar", "🇲🇳", 3.43),
  #("myanmar", "naypyidaw", "🇲🇲", 54.8),
  #("nepal", "kathmandu", "🇳🇵", 30.03),
  #("north korea", "pyongyang", "🇰🇵", 26.01),
  #("oman", "muscat", "🇴🇲", 5.3),
  #("pakistan", "islamabad", "🇵🇰", 231.4),
  #("philippines", "manila", "🇵🇭", 115.56),
  #("qatar", "doha", "🇶🇦", 2.93),
  #("saudi arabia", "riyadh", "🇸🇦", 35.95),
  #("singapore", "singapore", "🇸🇬", 5.64),
  #("south korea", "seoul", "🇰🇷", 51.74),
  #("sri lanka", "kotte", "🇱🇰", 21.09),
  #("syria", "damascus", "🇸🇾", 18.28),
  #("taiwan", "taipei", "🇹🇼", 23.57),
  #("tajikistan", "dushanbe", "🇹🇯", 9.96),
  #("thailand", "bangkok", "🇹🇭", 69.95),
  #("turkey", "ankara", "🇹🇷", 86.34),
  #("turkmenistan", "ashgabat", "🇹🇲", 6.13),
  #("united arab emirates", "abu dhabi", "🇦🇪", 10.08),
  #("uzbekistan", "tashkent", "🇺🇿", 35.27),
  #("vietnam", "hanoi", "🇻🇳", 98.17),
  #("yemen", "sana'a", "🇾🇪", 33.0),
]

const oceania = [
  #("australia", "canberra", "🇦🇺", 25.69),
  #("fiji", "suva", "🇫🇯", 0.91), #("kiribati", "tarawa", "🇰🇮", 0.12),
  #("marshall islands", "majuro", "🇲🇭", 0.06),
  #("micronesia", "palikir", "🇫🇲", 0.11),
  #("nauru", "yaren district", "🇳🇷", 0.01),
  #("new zealand", "wellington", "🇳🇿", 5.13),
  #("palau", "ngerulmud", "🇵🇼", 0.02),
  #("papua new guinea", "port moresby", "🇵🇬", 9.12),
  #("samoa", "apia", "🇼🇸", 0.2),
  #("solomon islands", "honiara", "🇸🇧", 0.72),
  #("tonga", "nuku'alofa", "🇹🇴", 0.11),
  #("tuvalu", "funafuti", "🇹🇻", 0.01),
  #("vanuatu", "port vila", "🇻🇺", 0.32),
]
